### ISSUE TITLE
Typecov warns on try/catch error 

### ISSUE THREAD

**Issue by bodinsamuel** [codechecks/typecov#11]
Hey,

Typecov warns on the `catch(e)`
```js
try {
 throw new Error()
} catch(e) {
  console.log(e);
}
```

But Typescript warns with this `Catch clause variable cannot have a type annotation`

Typecov should ignore `catch`

**Comment by krzkaczor** [comment]
This issue belongs to: https://github.com/plantain-00/type-coverage 

Please recreate it there.

**Comment by bodinsamuel** [comment]
yeah anyway I saw that I should enable flag on Typescript 👌
