### ISSUE TITLE
`New untyped symbols: 0` should never fail

### ISSUE THREAD

**Issue by JounQin** [codechecks/typecov#13]
`Change: +100.00% Total: 100.00% (min. 100.00%) New untyped symbols: 0`

https://github.com/rx-ts/prettier/pull/50/checks?check_run_id=409570509

**Comment by NoxHarmonium** [comment]
This is because the comparison at https://github.com/codechecks/typecov/blob/492faa968160adc7d212617fb9c5bd7843d7e5d5/src/index.ts#L47 uses `>` rather than `>=`.

I came across the same issue because my `atLeast` setting is 100.

I'm raising a PR to address it.

**Comment by krzkaczor** [comment]
Published as `typecov@0.2.2`

**Comment by JounQin** [comment]
@krzkaczor Is [@codechecks/type-coverage-watcher](https://www.npmjs.com/package/@codechecks/type-coverage-watcher) deprecated in favor of `typecov`? The npm package is not marked as deprecated but stale.

**Comment by krzkaczor** [comment]
@JounQin yes. Please use `typecov`. I will deprecate `@codechecks/type-coverage-watcher` soon. Sorry for the confusion.
